name: Build and test Python package

# adapted from https://github.com/mkoeppe/sage-numerical-backends-coin
on: [push, pull_request]

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  passagemath:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install test prerequisites
        run: pip install tox
      - name: Test package
        run: tox -e passagemath
